#pragma once

#define WG_DEVICE_LOCAL_IP "ENTER_DEVICE_WG_IP"
#define WG_DEVICE_PRIVATE_KEY "ENTER_DEVICE_PRIVATE_KEY"

#define WG_SERVER_PUBLIC_IP "46.250.238.190"
#define WG_SERVER_PUBLIC_KEY "vaZh5SWIXKNDJyT0sOPL3W5CNWqulMPAYLw9EV3pvTk="
#define WG_ENDPOINT_PORT 51820
